R-18(2018.1.19)




[180] 1ߺȯ_⵵.csv  ͸  ׷ ϼ.

dis <- read.csv("c:/r/1ߺȲ_⵵.csv", header = T, stringsAsFactors = F)

```{r}
dis
```

```{r}
library("reshape2") 
m_dis <- melt(dis)
m_dis
```


 - sol.1
```{r}
library(ggplot2)
library(colorspace)

ggplot(m_dis, aes(x = ⵵, y = log(value), group = variable, colour = variable))+
  geom_line()+
  geom_point()+
  labs(title = "1  ߺȲ(⵵)", y = "ο(log)")+
  guides(fill = guide_legend(title = ""))+
  theme(legend.title.align=0.5, legend.box.background = element_rect(),
        legend.box.margin = margin(t=0.1,r=0.1, b=0.1, l=0.1,unit='cm'))+
  theme(panel.grid.major.x = element_line(colour = rainbow_hcl(9), linetype = "dashed"), 
        panel.grid.minor.x = element_line(colour = rainbow_hcl(9), linetype = "dashed"),
        panel.grid.major.y = element_line(colour = rainbow_hcl(9), linetype = "dashed"),
        panel.grid.minor.y = element_line(colour = rainbow_hcl(9), linetype = "dashed"))
```



 - sol.2
```{r}
library(ggplot2)
ggplot(m_dis, aes(x = ⵵, y = value, group = variable, colour = variable))+
  geom_line()+
  geom_point()+
  labs(title = "1  ߺȲ(⵵)", y = "ο")+
  guides(fill = guide_legend(title = ""))+
  facet_wrap(~variable, scales = "free")+
  theme(axis.text.x = element_text(angle = 25, size = 7),
        legend.title.align=0.5, legend.box.background = element_rect(),
        legend.box.margin = margin(t=0.1,r=0.1, b=0.1, l=0.1,unit='cm'))
```



 -  Ǯ 
```{r}
dis
ggplot(m_dis,aes(x=⵵,y=value,group = variable))+
 geom_col(aes(fill=variable),position="dodge")+
 geom_text(aes(label = value),position=position_dodge(0.9),vjust=0)+
 ggtitle("1ߺȯ",subtitle="⵵")+
 theme(plot.title = element_text(lineheight=.8, face="bold",color="darkblue",hjust=0.5))+
 theme(plot.subtitle = element_text(lineheight=.8, face="bold",color="darkblue",hjust=0.5))+
 labs(colour="")
```
 



I am a student

 лԴϴ.

縦 ̾Ƴ?   װ ڰ?


```{r}
install.packages("KoNLP")
library("KoNLP")              #  jdk ġؾ  
```


 - 
 
```{r}
useSejongDic()
```


```{r}
text1 <- "R ¼ҽ , н, , , ׷Ƚ ̸ پ  Ű ߰ ִ  α׷̴."
```


```{r}
str_split(text1, ' ')  # stringr package
```



```{r}
strsplit(text1,'')
```



 - extractNoun() : ѱ 縦 ϴ Լ(ѳ м)
     
          
          (٣) : 繰, ,  ̸ Ÿ ǰ̴.
     
```{r}
extractNoun(text1)
```
 

 - SimplePos09() : ѱ ǰ縦 ϴ Լ

```{r}
text2 <- SimplePos09(text1)
```


 - str_match :  ġ Ǵ  ã 
 
```{r}
text_noun <- str_match(text2, '([A-Z-R]+)/N')  # + :  ѹ ִ´ 
as.vector(na.omit(text_noun[,2]))
```


```{r}
str_locate(grep('N',text2, value = T),'/N')
```



```{r}
extractNoun(text1)
```


```{r}
.libPaths()
```

C:\Users\STU\Documents\R\win-library\3.4\KoNLP_dic\current : ()  


 -  ȣϴ    ܾ ʱȭ 

```{r}
useSejongDic()
dic_user.txt
```

 - dic ߰ 
```{r}
buildDictionary(ext_dic = "sejong", 
                user_dic = data.frame(c("н", "", "پ"), c("ncn")),
                replace_usr_dic = T)
```




```{r}
extractNoun(text1)
```



----------------------------------------------------------------------------------------------------------------

#  ܾ 󵵼(wordclound Ȱ)

```{r}
install.packages("wordcloud")
library("wordcloud")
```


 - readLines() : line о帲 
```{r}
text <- readLines("c:/r/δӻ.txt")
text
```


```{r}
noun1 <- unlist(extractNoun(text))
```

```{r}
noun1 <- setdiff(noun1, '')
noun1 <- str_replace(noun1, "", "")
```


```{r}
noun2 <- unlist(sapply(text, extractNoun, USE.NAMES = FALSE))
unlist(lapply(text, extractNoun))
```


 - table : vector Ǽ 

```{r}
word_cn1 <- table(noun1) 
word_cn2 <- table(noun2)
```



```{r}
head(sort(word_cn1, decreasing = TRUE), 10)
```



```{r}
pal <- brewer.pal(8, "Dark2") ; pal

wordcloud(names(word_cn1), freq = word_cn1, scale = c(5,.5),
          random.order = FALSE, rot.per = .1, colors = pal)
```



    names :  ܾ
    freq : 󵵼
    scale :  ũ c(ū, )
    min.freq : ּ 󵵼 
    max.words : ̰ ̻ 󵵼 
    random.order : µǴ  Ƿ   
    random.color :   Ƿ  
    rot.per : ܾġ 90  
    colors : µ ܾ  


```{r}
word_df <- as.data.frame(word_cn1)
names(word_df) <- c("word","cnt")

orderBy(~-cnt,word_df)
word_df <- word_df[1 < str_length(word_df$word) & word_df$cnt >= 5,]

word_df$word<-gsub("\\S","",word_df$word)

barplot(word_df$cnt, names.arg = word_df$word, las = 2)

str_c("","α")
```





--------------------------------------------------------------------------------------------------------------

```{r}
install.packages("wordcloud2")
library(wordcloud2)
```



```{r}
fl <- c("  ̸ ҷֱ  
         ״ ٸ 
         ϳ   ʾҴ. 

           ̸ ҷ־  
         ״ Է ͼ 
          Ǿ. 

           ̸ ҷ ó 
            ⿡ ˸´ 
           ̸ ҷ ٿ. 
         ׿Է   
           ǰ ʹ. 

          츮  
            ǰ ʹ. 
            ʿ ʴ  
            ʴ ϳ ǹ̰ ǰ ʹ." )
wordcloud2(table(extractNoun(fl)))
```



```{r}

empty_house <- " Ұ  
                 ְŶ, ªҴ 
                â  ܿ Ȱ
                ƹ͵ 𸣴 Yҵ,  ְŶ
                 ٸ  ̵
                 ϴ 
                 ְŶ,  ̻   ƴ 
                ó   Ÿ  ׳
                    "

emp_house_cnt <- table(extractNoun(empty_house))

class(emp_house_cnt)

wordcloud2(emp_house_cnt)
```


```{r}
eh <- melt(emp_house_cnt)
names(eh) <- c("word","cnt")
eh

ggplot(eh, aes(x = word, y = cnt, fill = word))+
  geom_bar(stat = "identity")
```





```{r}
wordcloud2(word_cn2, shape = "triangle")
wordcloud2(table(c("")))
Map(extractNoun, text)
```





```{r}
table(str_match(SimplePos09(text), '([A-Z-R]+)/N')[,2])
```







```{r}
m <- melt(fruits_sales, id = c('name','year'))
m
dcast(m, name+year~variable)
```















